### ISSUE TITLE
Text is very small

### ISSUE THREAD

**Issue by caisah** [fourier/borland-blue-theme#2]
I have loaded the theme but the text is very very small. Zooming in doesn't solve the problem.
This is what I see
![borland](https://cloud.githubusercontent.com/assets/1536049/12377547/3dfc1bd6-bd2a-11e5-9f9d-26e183c7740e.png)

After I restart Emacs the text looks good though.

**Comment by fourier** [comment]
It should be fixed now.

**Comment by caisah** [comment]
Yep, thanks!
